
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Scanner;
import java.util.concurrent.Semaphore;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Guillermo H && @Bernardo B
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    Buffer BufTrenza = new Buffer();
    Buffer BufPlantilla = new Buffer();
    Buffer BufSuela = new Buffer();
    Semaphore ProducTrenza = new Semaphore(50);    //Semaforo Productor
    Semaphore ConsumTrenza = new Semaphore(0);    //Semaforo Consumidor
    Semaphore ProducSuela = new Semaphore(12);    //Semaforo Suela Productor
    Semaphore ConsumSuela = new Semaphore(0);     //Semaforo Suela Consumidor
    Semaphore ProducPlantilla = new Semaphore(7); //Semaforo Plantilla Productor
    Semaphore ConsumPlantilla = new Semaphore(0); //Semaforo Plantilla Consumidor
    

    
    ArrayList<ProdTrenza> listaProdT = new ArrayList<ProdTrenza>();
    ArrayList<ProdSuela> listaProdS = new ArrayList<ProdSuela>();
    ArrayList<Prodplantilla> listaProdP = new ArrayList<Prodplantilla>();
    ArrayList<Ensamblar> listaEnsam = new ArrayList<Ensamblar>();
       
    
    
    
    public Interfaz() {
        initComponents();
        SumarTrenza.setEnabled(false);
        RestarTrenza.setEnabled(false);
        SumarSuela.setEnabled(false);
        RestarSuela.setEnabled(false);
        SumarPlantilla.setEnabled(false);
        RestarPlantilla.setEnabled(false);
        BotonDetProduc.setEnabled(false);
        BotonDetEnsam.setEnabled(false);
        AreaProduccion.setEditable(false);
        AreaEnsamblaje1.setEditable(false);
        Ptipo1.setVisible(false);
        Ptipo2.setVisible(false);
        
        ArchivoTexto at = new ArchivoTexto();
        System.out.println("tipo1: "+at.ExtraerTipo1()+" tipo2: "+at.ExtraerTipo2());
        BufTrenza.setTipo1(at.ExtraerTipo1());
        BufTrenza.setTipo2(at.ExtraerTipo2());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        BotonIniProduc = new javax.swing.JButton();
        BotonDetProduc = new javax.swing.JButton();
        BotonIniEnsam = new javax.swing.JButton();
        BotonDetEnsam = new javax.swing.JButton();
        ProgressBarT = new javax.swing.JProgressBar();
        ProgressBarS = new javax.swing.JProgressBar();
        ProgressBarP = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SumarTrenza = new javax.swing.JButton();
        SumarSuela = new javax.swing.JButton();
        SumarPlantilla = new javax.swing.JButton();
        RestarTrenza = new javax.swing.JButton();
        RestarSuela = new javax.swing.JButton();
        RestarPlantilla = new javax.swing.JButton();
        OperadoresTrenzas = new javax.swing.JTextField();
        OperadoresSuelas = new javax.swing.JTextField();
        OperadoresPlantillas = new javax.swing.JTextField();
        ToggleEnsamblaje = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pausaProd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaProduccion = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        pausaEnsam = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaEnsamblaje1 = new javax.swing.JTextArea();
        Ptipo1 = new javax.swing.JPanel();
        labeltipo4 = new javax.swing.JLabel();
        giftipo4 = new javax.swing.JLabel();
        Ptipo2 = new javax.swing.JPanel();
        giftipo2 = new javax.swing.JLabel();
        labeltipo2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        BotonIniProduc.setText("Inciar Produccion");
        BotonIniProduc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonIniProducMouseClicked(evt);
            }
        });
        BotonIniProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniProducActionPerformed(evt);
            }
        });

        BotonDetProduc.setText("Detener Produccion");
        BotonDetProduc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonDetProducMouseClicked(evt);
            }
        });
        BotonDetProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDetProducActionPerformed(evt);
            }
        });

        BotonIniEnsam.setText("Iniciar Ensamblaje");
        BotonIniEnsam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonIniEnsamMouseClicked(evt);
            }
        });
        BotonIniEnsam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniEnsamActionPerformed(evt);
            }
        });

        BotonDetEnsam.setText("Detener Ensamblaje");
        BotonDetEnsam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonDetEnsamMouseClicked(evt);
            }
        });
        BotonDetEnsam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDetEnsamActionPerformed(evt);
            }
        });

        ProgressBarT.setMaximum(50);
        ProgressBarT.setStringPainted(true);

        ProgressBarS.setMaximum(12);
        ProgressBarS.setStringPainted(true);

        ProgressBarP.setMaximum(7);
        ProgressBarP.setStringPainted(true);

        jLabel1.setText("Trenzas:");

        jLabel2.setText("Suelas:");

        jLabel3.setText("Plantillas:");

        SumarTrenza.setText("+");
        SumarTrenza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SumarTrenzaMouseClicked(evt);
            }
        });
        SumarTrenza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumarTrenzaActionPerformed(evt);
            }
        });

        SumarSuela.setText("+");
        SumarSuela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SumarSuelaMouseClicked(evt);
            }
        });
        SumarSuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumarSuelaActionPerformed(evt);
            }
        });

        SumarPlantilla.setText("+");
        SumarPlantilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SumarPlantillaMouseClicked(evt);
            }
        });
        SumarPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumarPlantillaActionPerformed(evt);
            }
        });

        RestarTrenza.setText("-");
        RestarTrenza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestarTrenzaMouseClicked(evt);
            }
        });
        RestarTrenza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestarTrenzaActionPerformed(evt);
            }
        });

        RestarSuela.setText("-");
        RestarSuela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestarSuelaMouseClicked(evt);
            }
        });
        RestarSuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestarSuelaActionPerformed(evt);
            }
        });

        RestarPlantilla.setText("-");
        RestarPlantilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestarPlantillaMouseClicked(evt);
            }
        });

        OperadoresTrenzas.setText("3");
        OperadoresTrenzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperadoresTrenzasActionPerformed(evt);
            }
        });

        OperadoresSuelas.setText("2");
        OperadoresSuelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperadoresSuelasActionPerformed(evt);
            }
        });

        OperadoresPlantillas.setText("1");
        OperadoresPlantillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperadoresPlantillasActionPerformed(evt);
            }
        });

        ToggleEnsamblaje.setMaximum(1);
        ToggleEnsamblaje.setMinorTickSpacing(1);
        ToggleEnsamblaje.setValue(0);
        ToggleEnsamblaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToggleEnsamblajeMouseClicked(evt);
            }
        });

        jLabel4.setText("1 Ensamblador");

        jLabel5.setText("2 Ensambladores");

        jLabel6.setText("Ensambladores:");

        jLabel8.setText("Produccion:");

        pausaProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pausa3.png"))); // NOI18N

        AreaProduccion.setColumns(20);
        AreaProduccion.setRows(5);
        jScrollPane1.setViewportView(AreaProduccion);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pausaProd)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pausaProd)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pausaEnsam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pausa3.png"))); // NOI18N

        AreaEnsamblaje1.setColumns(20);
        AreaEnsamblaje1.setRows(5);
        jScrollPane2.setViewportView(AreaEnsamblaje1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pausaEnsam)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pausaEnsam)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        labeltipo4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeltipo4.setText("Tipo 1 en produccion");

        giftipo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animated-shoe-image-0055.gif"))); // NOI18N

        javax.swing.GroupLayout Ptipo1Layout = new javax.swing.GroupLayout(Ptipo1);
        Ptipo1.setLayout(Ptipo1Layout);
        Ptipo1Layout.setHorizontalGroup(
            Ptipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ptipo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Ptipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(giftipo4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labeltipo4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        Ptipo1Layout.setVerticalGroup(
            Ptipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ptipo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Ptipo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labeltipo4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Ptipo1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(giftipo4)))
                .addContainerGap())
        );

        giftipo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animated-shoe-image-0037.gif"))); // NOI18N

        labeltipo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeltipo2.setText("Tipo 2 en produccion");

        javax.swing.GroupLayout Ptipo2Layout = new javax.swing.GroupLayout(Ptipo2);
        Ptipo2.setLayout(Ptipo2Layout);
        Ptipo2Layout.setHorizontalGroup(
            Ptipo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ptipo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Ptipo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(giftipo2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labeltipo2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        Ptipo2Layout.setVerticalGroup(
            Ptipo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ptipo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Ptipo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Ptipo2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(giftipo2))
                    .addComponent(labeltipo2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProgressBarT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProgressBarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProgressBarS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RestarTrenza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OperadoresTrenzas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SumarTrenza))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RestarPlantilla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OperadoresPlantillas, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SumarPlantilla))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RestarSuela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OperadoresSuelas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SumarSuela)))
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(BotonIniProduc, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(BotonIniEnsam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(BotonDetProduc)
                                    .addGap(18, 18, 18)
                                    .addComponent(BotonDetEnsam))
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addComponent(jLabel8)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ToggleEnsamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5)
                            .addGap(82, 82, 82))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(175, 175, 175)
                            .addComponent(jLabel6)
                            .addGap(203, 203, 203))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Ptipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ptipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonIniProduc)
                    .addComponent(BotonIniEnsam))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonDetProduc)
                    .addComponent(BotonDetEnsam))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addComponent(ToggleEnsamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ptipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ptipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProgressBarT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SumarTrenza, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RestarTrenza, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(OperadoresTrenzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProgressBarS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SumarSuela, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RestarSuela, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(OperadoresSuelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProgressBarP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                .addComponent(RestarPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(OperadoresPlantillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SumarPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OperadoresTrenzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperadoresTrenzasActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(OperadoresTrenzas.getText())==1)
            RestarTrenza.setEnabled(false);
    }//GEN-LAST:event_OperadoresTrenzasActionPerformed

    private void SumarTrenzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SumarTrenzaMouseClicked
        // TODO add your handling code here:
        int sum = Integer.parseInt(OperadoresTrenzas.getText());
        sum++;
        OperadoresTrenzas.setText(Integer.toString(sum));
        agregarProdT(1);
    }//GEN-LAST:event_SumarTrenzaMouseClicked

    private void RestarTrenzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestarTrenzaMouseClicked
        // TODO add your handling code here:
        if(Integer.parseInt(OperadoresTrenzas.getText())>0)
        {
            int res = Integer.parseInt(OperadoresTrenzas.getText());
            res--;
            OperadoresTrenzas.setText(Integer.toString(res));
        AreaProduccion.append("-Se paro el productor de trenzas "+(listaProdT.size()-1)+"-\n");
        listaProdT.get(listaProdT.size()-1).stop();
        listaProdT.remove(listaProdT.size()-1);
        }
    }//GEN-LAST:event_RestarTrenzaMouseClicked

    private void SumarSuelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SumarSuelaMouseClicked
        int sum = Integer.parseInt(OperadoresSuelas.getText());
        sum++;
        OperadoresSuelas.setText(Integer.toString(sum));
        agregarProdS(1);
    }//GEN-LAST:event_SumarSuelaMouseClicked

    private void RestarSuelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestarSuelaMouseClicked
        // TODO add your handling code here:
        if(Integer.parseInt(OperadoresSuelas.getText())>0)
        {
            int res = Integer.parseInt(OperadoresSuelas.getText());
            res--;
            OperadoresSuelas.setText(Integer.toString(res));
            
            AreaProduccion.append("-Se paro el productor de suela "+(listaProdS.size()-1)+"-\n");
            listaProdS.get(listaProdS.size()-1).stop();
            listaProdS.remove(listaProdS.size()-1);
        }
    }//GEN-LAST:event_RestarSuelaMouseClicked

    private void SumarPlantillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SumarPlantillaMouseClicked
        // TODO add your handling code here:
        int sum = Integer.parseInt(OperadoresPlantillas.getText());
        sum++;
        OperadoresPlantillas.setText(Integer.toString(sum));
        agregarProdP(1);
    }//GEN-LAST:event_SumarPlantillaMouseClicked

    private void RestarPlantillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestarPlantillaMouseClicked
        // TODO add your handling code here:
        if(Integer.parseInt(OperadoresPlantillas.getText())>0)
        {
            int res = Integer.parseInt(OperadoresPlantillas.getText());
            res--;
            OperadoresPlantillas.setText(Integer.toString(res));
            
            AreaProduccion.append("-Se paro el productor de plantilla "+(listaProdP.size()-1)+"-\n");
            listaProdP.get(listaProdP.size()-1).stop();
            listaProdP.remove(listaProdP.size()-1);
        }
    }//GEN-LAST:event_RestarPlantillaMouseClicked

    private void ToggleEnsamblajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToggleEnsamblajeMouseClicked
        // TODO add your handling code here:

        if(ToggleEnsamblaje.getValue() == 1)
        {   
            if(listaEnsam.size() == 1){
                listaEnsam.add(1, new Ensamblar(BufTrenza, BufSuela, BufPlantilla, ProducTrenza, ConsumTrenza, ProducSuela, ConsumSuela, ProducPlantilla, ConsumPlantilla, ProgressBarT, ProgressBarS, ProgressBarP, "Ensamblador 2",AreaEnsamblaje1, AreaProduccion, Ptipo1, Ptipo2 ));
                listaEnsam.get(1).start();
                AreaEnsamblaje1.append("****** Se Agrego un Ensamblador ******\n");
            }  
        }
         if(ToggleEnsamblaje.getValue() == 0)
        {
            listaEnsam.get(1).stop();
            listaEnsam.remove(1);
            AreaEnsamblaje1.append("****** Se Quito un Ensamblador ******\n");
        }
    }//GEN-LAST:event_ToggleEnsamblajeMouseClicked

    private void BotonIniProducMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonIniProducMouseClicked
        // TODO add your handling code here:
//        System.out.println("Numero de productores T en iniciar todos: "+Integer.parseInt(OperadoresTrenzas.getText()));
//        for (int i = 0; i < Integer.parseInt(OperadoresTrenzas.getText()); i++) {
//            agregarProdT();
//        }
        agregarProdT(Integer.parseInt(OperadoresTrenzas.getText()));
        agregarProdS(Integer.parseInt(OperadoresSuelas.getText()));
        agregarProdP(Integer.parseInt(OperadoresPlantillas.getText()));
        SumarTrenza.setEnabled(true);
        RestarTrenza.setEnabled(true);
        SumarSuela.setEnabled(true);
        RestarSuela.setEnabled(true);
        SumarPlantilla.setEnabled(true);
        RestarPlantilla.setEnabled(true);
        BotonDetProduc.setEnabled(true);
        
        
    }//GEN-LAST:event_BotonIniProducMouseClicked

    private void BotonDetProducMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDetProducMouseClicked
        // TODO add your handling code here:
        pararProd();
    }//GEN-LAST:event_BotonDetProducMouseClicked

    private void BotonIniEnsamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonIniEnsamMouseClicked
        // TODO add your handling code here:
      BotonDetEnsam.setEnabled(true);
        if(ToggleEnsamblaje.getValue() == 0)
        {   
            listaEnsam.add(new Ensamblar(BufTrenza, BufSuela, BufPlantilla, ProducTrenza, ConsumTrenza, ProducSuela, ConsumSuela, ProducPlantilla, ConsumPlantilla, ProgressBarT, ProgressBarS, ProgressBarP, "Ensamblador 1",AreaEnsamblaje1, AreaProduccion, Ptipo1, Ptipo2 ));
            listaEnsam.get(0).start();
            AreaEnsamblaje1.append("****** Empezo el Ensamblador 1 ******\n");
        }
         if(ToggleEnsamblaje.getValue() == 1)
        {
            listaEnsam.add(new Ensamblar(BufTrenza, BufSuela, BufPlantilla, ProducTrenza, ConsumTrenza, ProducSuela, ConsumSuela, ProducPlantilla, ConsumPlantilla, ProgressBarT, ProgressBarS, ProgressBarP, "Ensamblador 1",AreaEnsamblaje1, AreaProduccion, Ptipo1, Ptipo2 ));
            listaEnsam.get(0).start();
            AreaEnsamblaje1.append("****** Empezo el Ensamblador 1 ******\n");
            listaEnsam.add(new Ensamblar(BufTrenza, BufSuela, BufPlantilla, ProducTrenza, ConsumTrenza, ProducSuela, ConsumSuela, ProducPlantilla, ConsumPlantilla, ProgressBarT, ProgressBarS, ProgressBarP, "Ensamblador 2",AreaEnsamblaje1, AreaProduccion, Ptipo1, Ptipo2 ));
            listaEnsam.get(1).start();
            AreaEnsamblaje1.append("****** Empezo el Ensamblador 2 ******\n");
        }
        
    }//GEN-LAST:event_BotonIniEnsamMouseClicked

    private void BotonDetEnsamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDetEnsamMouseClicked
        // TODO add your handling code here:
        int i = listaEnsam.size()-1; 
        while(i >= 0){
            listaEnsam.get(i).stop();
            AreaEnsamblaje1.append("****** Ensamblador "+i+" parado ******\n");
            listaEnsam.remove(i);
            i--;
        }
            
            
    }//GEN-LAST:event_BotonDetEnsamMouseClicked

    private void BotonIniProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniProducActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonIniProducActionPerformed

    private void SumarTrenzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumarTrenzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SumarTrenzaActionPerformed

    private void OperadoresSuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperadoresSuelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OperadoresSuelasActionPerformed

    private void OperadoresPlantillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperadoresPlantillasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OperadoresPlantillasActionPerformed

    private void BotonDetEnsamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDetEnsamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonDetEnsamActionPerformed

    private void BotonDetProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDetProducActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonDetProducActionPerformed

    private void BotonIniEnsamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniEnsamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonIniEnsamActionPerformed

    private void SumarSuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumarSuelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SumarSuelaActionPerformed

    private void RestarTrenzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestarTrenzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RestarTrenzaActionPerformed

    private void RestarSuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestarSuelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RestarSuelaActionPerformed

    private void SumarPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumarPlantillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SumarPlantillaActionPerformed

    public void agregarProdT(int a){
        while(a > 0){
        listaProdT.add(new ProdTrenza(BufTrenza, Integer.toString(listaProdT.size())  ,ProducTrenza, ConsumTrenza, ProgressBarT,AreaProduccion));
        listaProdT.get(listaProdT.size()-1).start();
        
        AreaProduccion.append("+Nuevo productor de Trenzas+ "+(listaProdT.size()-1)+"\n");
        a--;
        try {
            Thread.sleep(200);                
        } catch(InterruptedException ex) {
            Thread.currentThread().interrupt();
        }
        }
    }
    
    public void agregarProdS(int a){
        while(a > 0){
        listaProdS.add(new ProdSuela(BufSuela, Integer.toString(listaProdS.size())  ,ProducSuela, ConsumSuela, ProgressBarS,AreaProduccion));
        listaProdS.get(listaProdS.size()-1).start();
        
        AreaProduccion.append("+Nuevo productor de Suela+ "+(listaProdS.size()-1)+"\n");
        a--;
            try {
                Thread.sleep(200);                
            } catch(InterruptedException ex) {
                Thread.currentThread().interrupt();
            }
        }
    }
    
    public void agregarProdP(int a){
        while(a > 0){
        listaProdP.add(new Prodplantilla(BufPlantilla, Integer.toString(listaProdP.size())  ,ProducPlantilla, ConsumPlantilla, ProgressBarP,AreaProduccion));
        listaProdP.get(listaProdP.size()-1).start();
        
        AreaProduccion.append("+Nuevo productor de Plantillas+ "+(listaProdP.size()-1)+"\n");
        a--;
        try {
            Thread.sleep(200);                
        } catch(InterruptedException ex) {
            Thread.currentThread().interrupt();
        }
        }
    }
    
    public void pararProd (){
        int i = listaProdT.size()-1; 
        while(i >= 0){
            listaProdT.get(i).stop();
            AreaProduccion.append("-Productor de Trenzas "+i+" parado-\n");
            listaProdT.remove(i);
            i--;
        }
        i = listaProdS.size()-1; 
        while(i >= 0){
            listaProdS.get(i).stop();
            AreaProduccion.append("-Productor de Suelas "+i+" parado-\n");
            listaProdS.remove(i);
            i--;
        }
        i = listaProdP.size()-1; 
        while(i >= 0){
            listaProdP.get(i).stop();
            AreaProduccion.append("-Productor de Plantillas "+i+" parado-\n");
            listaProdP.remove(i);
            i--;
        }
        
        
    }  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaEnsamblaje1;
    private javax.swing.JTextArea AreaProduccion;
    private javax.swing.JButton BotonDetEnsam;
    private javax.swing.JButton BotonDetProduc;
    private javax.swing.JButton BotonIniEnsam;
    private javax.swing.JButton BotonIniProduc;
    private javax.swing.JTextField OperadoresPlantillas;
    private javax.swing.JTextField OperadoresSuelas;
    private javax.swing.JTextField OperadoresTrenzas;
    private javax.swing.JProgressBar ProgressBarP;
    private javax.swing.JProgressBar ProgressBarS;
    private javax.swing.JProgressBar ProgressBarT;
    private javax.swing.JPanel Ptipo1;
    private javax.swing.JPanel Ptipo2;
    private javax.swing.JButton RestarPlantilla;
    private javax.swing.JButton RestarSuela;
    private javax.swing.JButton RestarTrenza;
    private javax.swing.JButton SumarPlantilla;
    private javax.swing.JButton SumarSuela;
    private javax.swing.JButton SumarTrenza;
    private javax.swing.JSlider ToggleEnsamblaje;
    private javax.swing.JLabel giftipo2;
    private javax.swing.JLabel giftipo4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labeltipo2;
    private javax.swing.JLabel labeltipo4;
    private javax.swing.JLabel pausaEnsam;
    private javax.swing.JLabel pausaProd;
    // End of variables declaration//GEN-END:variables
}
